CREATE TABLE skills (
    id SERIAL PRIMARY KEY,
    concepttype VARCHAR(100),
    concepturi VARCHAR(255),
    skilltype VARCHAR(100),
    reuselevel VARCHAR(50),
    preferredlabel VARCHAR(255),
    altlabels TEXT,
    hiddenlabels TEXT,
    status VARCHAR(50),
    modifieddate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    scopenote TEXT,
    definition TEXT,
    inscheme TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    originalskilluri TEXT,
    originalskilltype VARCHAR(100),
    broaderconcepturi TEXT,
    broadertype VARCHAR(100),
    code TEXT,
    level0uri TEXT,
    level0preferredterm TEXT,
    level1uri TEXT,
    level1preferredterm TEXT,
    level2uri TEXT,
    level2preferredterm TEXT,
    level3uri TEXT,
    level3preferredterm TEXT,
    relationtype VARCHAR(100),
    broaderconceptpt TEXT,
    broaderuri TEXT,
    level0code TEXT,
    level1code TEXT,
    level2code TEXT,
    level3code TEXT,
    conceptschemeuri TEXT,
    occupationuri TEXT,
    iscogroup TEXT,
    relatedskilltype TEXT,
    skilluri TEXT,
    regulatedprofessionnote TEXT,
    relatedskilluri TEXT,
    title TEXT,
    hastopconcept TEXT
);


CREATE INDEX idx_concepts_preferredlabel ON skills(preferredlabel);
